#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the birthday function below.
def birthday(s, d, m):
    squares = 0
    temp = s[:m-1]
    print(temp)
    for i in s[m-1:]:
        # temp.insert(m-1, i)
        temp.append(i)
        # print(temp)
        if sum(temp) == d:
            squares += 1
        temp.pop(0)  # must pop 0
    return squares


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    s = list(map(int, input().rstrip().split()))

    dm = input().rstrip().split()

    d = int(dm[0])

    m = int(dm[1])

    result = birthday(s, d, m)
