#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the breakingRecords function below.
def breakingRecords(scores):

    high = [scores[0]]
    low = [scores[0]]
    for i in range(1,len(scores)):
        if scores[i] > max(high):
            high.append(scores[i])
        elif scores[i] < min(low):
            low.append(scores[i])
        else:
            pass
    return len(high)-1, len(low)-1

    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
